# Generated by Django 4.2.1 on 2023-06-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0002_alter_atleta_rm_backsquat_alter_atleta_rm_bench_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='apellido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
