# Generated by Django 4.2.1 on 2023-06-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0003_atleta_apellido_atleta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
