# Generated by Django 4.2.1 on 2023-06-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0004_alter_atleta_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='Fran',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='Grace',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='Isabel',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='Murph',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='RM_backsquat',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='RM_bench',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='RM_clean',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='RM_cleanandjerk',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='RM_deadlift',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='RM_jerk',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='RM_snatch',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='fecha_nacimiento',
        ),
    ]
