# Generated by Django 4.2.1 on 2023-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0005_remove_atleta_fran_remove_atleta_grace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='atleta',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
