# Generated by Django 4.2.1 on 2023-06-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0006_remove_atleta_apellido_remove_atleta_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='user',
        ),
        migrations.AddField(
            model_name='atleta',
            name='backsquat_rm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='clean_rm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='deadlift_rm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='fran_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='grace_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='jerk_rm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='murph_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='snatch_rm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='apodo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
    ]
