# Generated by Django 4.2.1 on 2023-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0007_remove_atleta_user_atleta_backsquat_rm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='apodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
