# Generated by Django 4.2.1 on 2023-06-14 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Atletas', '0008_alter_atleta_apodo_alter_atleta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
