# Generated by Django 4.2.1 on 2023-06-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0009_atleta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='fran_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='grace_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='murph_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
