# Generated by Django 4.2.1 on 2023-06-15 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Atletas', '0013_alter_score_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
