# Generated by Django 4.2.1 on 2023-06-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planificaciones', '0003_planificacion_planificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion',
            name='planificacion',
        ),
    ]
