# Generated by Django 4.2.1 on 2023-06-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planificaciones', '0004_remove_planificacion_planificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planificacion',
        ),
    ]
